title: Nicholas Kondo # your name (or website title) here
logo: "/images/Pro Headshot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a second year MBA student focused on Business Analytics and Machine Learning.  
  <br><br>
  Here is a list of my projects and coursework.  I have a strong interest in sports and I use R for coding.  Enjoy! 
  <br><br>
  <a href="https://www.linkedin.com/in/nicholaskondo/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
